---
- name: Configure base VM
  hosts: all
  become: yes
  vars_files:
    - ./vars/environment.yaml

  tasks:
    - name: Update system
      block:
        - name: Install hwclock
          ansible.builtin.apt:
            name: util-linux-extra
            state: present
        
        - name: Update clock
          ansible.builtin.command: hwclock --hctosys
          retries: 6
          delay: 5

        - name: Update apt
          ansible.builtin.apt:
            name: "*"
            state: latest
            update_cache: yes
            autoclean: yes
            autoremove: yes
    
  
    - name: Install Lmod
      block:
        - name: Create software space
          ansible.builtin.file:
            path: "{{ softwaredir }}"
            state: directory
            owner: root
            group: root
            mode: '0755'
        
        - name: Mount software space (ephemeral D:\HyperV\software)
          ansible.posix.mount:
            src: "//{{ winhost.ip }}/software"
            path: "{{ softwaredir }}"
            opts: "username={{ winhost.username  }},password={{ winhost.password }}"
            fstype: cifs
            state: mounted

        - name: Check if Lmod is installed
          ansible.builtin.command: which module
          register: lmod_stat
        
        - ansible.builtin.debug:
            var: lmod_stat
          when: vm_role == 'head'

        - name: Install lua for Lmod
          block:
            - name: Build Lmod dependencies
              ansible.builtin.apt:
                name: lmod
                state: build-dep
        
            - name: Obtain lua version
              ansible.builtin.command: which lua | xargs realpath -e | xargs basename
              register: luaversion


            - name: Ensure lua-dev and tcl-dev are also installed
              ansible.builtin.apt:
                name: 
                  - "lib{{ luaversion }}-dev"
                  - tcl-dev
                state: present

            - name: Checkout Lmod
              ansible.builtin.git:
                repo: 'https://github.com/TACC/Lmod'
                dest: "{{ installtempdir }}/lmod"
                version: 8.7.53
            
            - name: Install Lmod
              ansible.builtin.command:
                chdir: "{{ installtempdir }}/lmod"
                cmd: "./configure --prefix={{ softwaredir }} && make install"

            - name: Lmod init for shells
              ansible.builtin.file:
                src: "{{ softwaredir }}/lmod/lmod/init/{{ item.src }}"
                dest: "/etc/profile.d/z00_lmod{{ item.ext }}"
                state: link
              loop:
                - {src: profile, ext: .sh}
                - {src: cshrc, ext: .csh }
          when: no