---
- name: Configure base VM
  hosts: all
  become: yes
  vars_files:
    - ./vars/environment.yaml

  tasks:
    - name: Update system
      block:
        - name: Install hwclock
          ansible.builtin.apt:
            name: util-linux-extra
            state: present
        
        - name: Update clock
          ansible.builtin.command: hwclock --hctosys
          retries: 6
          delay: 5

        - name: Update apt
          ansible.builtin.apt:
            name: "*"
            state: latest
            update_cache: yes
            autoclean: yes
            autoremove: yes
    
    - name: Install Lmod
      ansible.builtin.include_role:
        name: idiv_biodiversity.lmod
      vars:
        lmod_prefix: lmod.prefix
        lmod_install: vm_role == "head"
        lmod_canary: lmod.canary
      tags:
        - lmod
        - modules
