#cloud-config
locale: en_GB.utf8
timezone: GMT

growpart:
  mode: auto
  devices: [/]
  ignore_growroot_disabled: false

keyboard:
  layout: gb
 
preserve_sources_list: true
package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - software-properties-common
  - eject
  - keyboard-configuration
  - git
  - python3-pip

users:
  - name: service
    lock_passwd: false
    gecos: Service User
    shell: /bin/bash
    groups: [users,admin,wheel]
    sudo: ALL=(ALL) NOPASSWD:ALL
chpasswd:
  expire: true
  users:
    - {name: service, password: password1, type: text}
ssh_pwauth: true

write_files:
  # PPA ansible
  - path: /usr/share/keyrings/ansible.gpg
    source:
      uri: https://raw.githubusercontent.com/tiborauer/ansible-win/hyperv/ansible/ansible.gpg
    owner: root:root
    permissions: 0o644
  - path: /etc/apt/sources.list.d/ansible.sources
    source:
      uri: https://raw.githubusercontent.com/tiborauer/ansible-win/hyperv/ansible/ansible.sources
    owner: root:root
    permissions: 0o644
  # SSH
  - path: /home/service/.ssh/id_rsa
    owner: service:service
    permissions: 0o600
    defer: true
    encoding: base64
    content: |
      LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFB
      QUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJsd0FBQUFkemMyZ3RjbgpOaEFBQUFB
      d0VBQVFBQUFZRUFuRURrYjBSMEJzdjJWMHhnZkROc3JwS2hjcHdlK2ZEWDVPTkk2dEF4dE5QeVJx
      TEFBUnlvCm5ZRFBzUTNvZlFOYyt5TE04bHdlNTRmV1VyK0FiblR3dlhOVkdubkowRXFXd0g3VWlY
      N3JDQU5rQmljd3RPb2xwYld5M3kKUzFrZkljc3BROHJBRWxJT3hnRzRpK2tMTzE0WnNZOUl4MVh1
      TGp3KzRKRlVZL2FXSW5mMlhVaVl2am5hdkp1SWJ6UnFMRwp3dTJ0clVIcFlQQlE1Y3p1MHpoQnZT
      YTE3MXBwMHM4QUdWUVlwUXV2ZkpCR083K0hYNDNuZEw3MENUVVhZeW8yMXNKRk42CmxoWWRycFU1
      bnliKzIxTUFqOWkrV2dISVFZbmVyYXhSSTM5alZDWGlxNkVtWDJKNlo1RmtUNjd0OFFwbHRRN3Ju
      ejIzQkEKcS92cklFaUgrcVdHRWhtYm9rWXZpOHRaTmtuTnZ5ZlBJOGFEV2FGdnRsNkEvRWxLUGtN
      aVErcXV2bXhoSXRscnJUb1VwbQp1Vk5qSzZBVUw0dUNtZmw1NzdYOE12b0pRbldOQW92eEIrNmNo
      UHdNcHJnRDdueEFMYXBkZVVNTjBRWmlpckRJVEVWcWRqCmtpUHpLNXpQYVdzOW51cFdnOEFwa2FJ
      QWlncEpPT21mRy9ubHNmNUhBQUFGaUw1Nm4vQytlcC93QUFBQUIzTnphQzF5YzIKRUFBQUdCQUp4
      QTVHOUVkQWJMOWxkTVlId3piSzZTb1hLY0h2bncxK1RqU09yUU1iVFQ4a2Fpd0FFY3FKMkF6N0VO
      NkgwRApYUHNpelBKY0h1ZUgxbEsvZ0c1MDhMMXpWUnA1eWRCS2xzQisxSWwrNndnRFpBWW5NTFRx
      SmFXMXN0OGt0Wkh5SExLVVBLCndCSlNEc1lCdUl2cEN6dGVHYkdQU01kVjdpNDhQdUNSVkdQMmxp
      SjM5bDFJbUw0NTJyeWJpRzgwYWl4c0x0cmExQjZXRHcKVU9YTTd0TTRRYjBtdGU5YWFkTFBBQmxV
      R0tVTHIzeVFSanUvaDErTjUzUys5QWsxRjJNcU50YkNSVGVwWVdIYTZWT1o4bQovdHRUQUkvWXZs
      b0J5RUdKM3Eyc1VTTi9ZMVFsNHF1aEpsOWllbWVSWkUrdTdmRUtaYlVPNjU4OXR3UUt2NzZ5Qklo
      L3FsCmhoSVptNkpHTDR2TFdUWkp6YjhuenlQR2cxbWhiN1plZ1B4SlNqNURJa1BxcnI1c1lTTFph
      NjA2RktacmxUWXl1Z0ZDK0wKZ3BuNWVlKzEvREw2Q1VKMWpRS0w4UWZ1bklUOERLYTRBKzU4UUMy
      cVhYbEREZEVHWW9xd3lFeEZhblk1SWo4eXVjejJscgpQWjdxVm9QQUtaR2lBSW9LU1RqcG54djU1
      YkgrUndBQUFBTUJBQUVBQUFHQVRoMnpGbDFtbEM5THpJRUdpNUU1K0Z5ZUVpCm95NGttaDVYQXJl
      QmoxZ0sybEplTWZrbTY5YldDRWRNTzdReVIzUzZZdVI4ditOMG9Wdi9DMVNJTjJCNEN0UHpzN3hj
      SkUKYzUvMHFYaW1ENitDUmdFNXZIaUNzY0dRMXpZSEFCdkdkUkRlOUM3dVhQTlBhUFNJTU5kblNv
      NjdmeWJwVnJLZm84aFJDaQozQWJmTUFSQlNvbU1zeTFCU2FHSUovQlFWRDBSZjZCL0EzdUpyc0Zy
      YkpmeGRVNWplQUpWVlNLbTRLWXA5RVl0N2dzS21BCk0wYWhhd2dLZXJjc1VaNFZQeUpPMStnd1F3
      Ly9MWlpJSkJVM3FmY1JMVGdrY09qaUFpczdMSnlrMDVOT3pkbWM0RVBvOHIKVGJEcUtweWNCRXJX
      bFZBMUlVdEc3bHJFSGwyR2c2a3ltQ2x5Z3BLUTFkRnlHNTdsRzV2SXRjR0V1cHE4eEFvNFV2dm1H
      SApaYW9mdGtMN3ZhMTNDSlhoMmVKV2pDcVFkckUxWDFRNXRVVFVibFhPaEZONlZyeEtPaUZiYWE0
      UjV5b1F5T2dmUVlnMnpQCmdEbnQyb0JNdW1QRkFReE1QcS9GbnM2eXlWVmV6a1luK24xZ3hRU1hs
      bG04SUdTUkJ4UERvSUoyZXlIcWY3djlrQkFBQUEKd0ZGN1hDQStYMFowaTk5SWVla21tbkcrQ2R0
      aG5WMHdsZ2VTQVZmNmd5SkxEbTlBOW9MOCtTM1BnUmtBTTFHNzA0NGozRgpTYWtJVENtVDBDT1Bx
      NWR2MVdURVJibi9vNks5ZTduRldlZU5YZk0zQkF1LzQ0WWJZNFBudFl6cHQ1TWVkeVZUSXJOZlUy
      CmNlRFRuQzZMUDJTaW1QZmpJRDJGcnBLeXJTTE1CKzdYUlB2ZS9YZzA1ZHFsWGhxeUFZQ2NjUXFw
      SFdnNWZQaFZmeFlaMG4KK1JqVkdLVE5hRVVuVDl4cWpOWTZDSmlJVmlWUVN6cmgzVlVwU01NU1Q5
      Ni9jaDlRQUFBTUVBMDlLMEVMOGRyejBrTzRzaApCbTVIbi81Wk54Y2hvMUxCT1IreEhkeDFQNHkw
      Vm1VTzhIcjJCNElEYytGV2RsSzgxWE9iL3dBRHF5bHkzUlVtOSt2R2dMClJ6L3AwUGxCTEZVNDhj
      VzBPN1ZnTkU5RTFoK0xFUEJ6TXNZb0wxZnlnOFZId1dCSGFTS1IzTEFESlFBQWJuNHo1UlBQc2MK
      THNIaDVQd28xZEdFSXVkZDdSOXlYU0FWa2lvRDZ6OGlNSVhxSmozOS9MZC9uK0cvcDhkSHFjM3Q0
      QWk4RUlhaFFiTzB3cQpvaTFMMXRvSXNQL25XamQ2d0tVMzlMOTRmOG9rVG5BQUFBd1FDODExQU9Z
      UHJ0TEs0YW5DNVdDVnVXNkRmdlVLeTBpTGR3CkcrRk1ncWhiaE45Mmo0OER6bk8weGFuVE1RNElm
      TTU3YnRrYjFCekxYSUpIN21adXBzaEkwZ2g0d3FuMkpRZWxFRk5mTUEKSnhWVWZHZWdDSVhmV1Vy
      L1V3Wi84THArWldIMlRVUE14U0hnTGpGenZmbXg3bGJjcDhXSW1vZkR5aVZsTFJocVk0cTNaTApC
      TG5YbENhUGxqdEJ0N29JNFNXeFF1clVxaHJSUUxpLytCQ1hscXJyRDBvQnJOM0hmL0t5R1NqZkNq
      R2pLOVV5MitYMVRzCjJuQUt6S2l1VUg3NkVBQUFBTmMyVnlkbWxqWlVCMmJTMHdNUUVDQXdRRkJn
      PT0KLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0tCg==

runcmd:
  # remove metadata iso
  - test -b /dev/cdrom && eject
  - test -b /dev/sr0 && eject /dev/sr0
  # disable cloud init on next boot (https://cloudinit.readthedocs.io/en/latest/topics/boot.html, https://askubuntu.com/a/1047618)
  - touch /etc/cloud/cloud-init.disabled
  # ansible
  - apt update
  - apt install ansible -y
  - ansible-galaxy role install idiv_biodiversity.lmod
  - mkdir /usr/share/ansible/roles -p
  - mkdir /home/service/.ansible/roles -p
  # prepare for ansible run
  - pip install keyring keyrings.cryptfile --break-system-packages
  - git clone https://github.com/tiborauer/ansible-win /home/service/deploy
  