#cloud-config
locale: en_GB.utf8
timezone: GMT

growpart:
  mode: auto
  devices: [/]
  ignore_growroot_disabled: false

keyboard:
  layout: gb

ssh_pwauth: false
users:
- name: service
  gecos: Service User
  groups: users,admin,wheel
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  lock_passwd: true
  ssh_authorized_keys:
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCcQORvRHQGy/ZXTGB8M2yukqFynB758Nfk40jq0DG00/JGosABHKidgM+xDeh9A1z7IszyXB7nh9ZSv4BudPC9c1UaecnQSpbAftSJfusIA2QGJzC06iWltbLfJLWR8hyylDysASUg7GAbiL6Qs7Xhmxj0jHVe4uPD7gkVRj9pYid/ZdSJi+Odq8m4hvNGosbC7a2tQelg8FDlzO7TOEG9JrXvWmnSzwAZVBilC698kEY7v4dfjed0vvQJNRdjKjbWwkU3qWFh2ulTmfJv7bUwCP2L5aAchBid6trFEjf2NUJeKroSZfYnpnkWRPru3xCmW1DuufPbcECr++sgSIf6pYYSGZuiRi+Ly1k2Sc2/J88jxoNZoW+2XoD8SUo+QyJD6q6+bGEi2WutOhSma5U2MroBQvi4KZ+Xnvtfwy+glCdY0Ci/EH7pyE/AymuAPufEAtql15Qw3RBmKKsMhMRWp2OSI/MrnM9paz2e6laDwCmRogCKCkk46Z8b+eWx/kc="
    
runcmd:
  # remove metadata iso
  - test -b /dev/cdrom && eject
  - test -b /dev/sr0 && eject /dev/sr0
  # disable cloud init on next boot (https://cloudinit.readthedocs.io/en/latest/topics/boot.html, https://askubuntu.com/a/1047618)
  - touch /etc/cloud/cloud-init.disabled